// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntButtonController from "./int_button_controller"
application.register("int-button", IntButtonController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RemoveSectionController from "./remove_section_controller"
application.register("remove-section", RemoveSectionController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import CollapsibleSectionsController from "./collapsible_sections_controller"
application.register("collapsible-sections", CollapsibleSectionsController)
