// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapsibleSectionsController from "./collapsible_sections_controller"
application.register("collapsible-sections", CollapsibleSectionsController)

import ConfirmBookingController from "./confirm_booking_controller"
application.register("confirm-booking", ConfirmBookingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntButtonController from "./int_button_controller"
application.register("int-button", IntButtonController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RemoveSectionController from "./remove_section_controller"
application.register("remove-section", RemoveSectionController)

import RenderItineraryInUserShowPageController from "./render_itinerary_in_user_show_page_controller"
application.register("render-itinerary-in-user-show-page", RenderItineraryInUserShowPageController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ToggleBookingButtonsController from "./toggle_booking_buttons_controller"
application.register("toggle-booking-buttons", ToggleBookingButtonsController)
