meta_product_name: "Triply"
meta_title: "Triply - Group travel made simple"
meta_description: "Struggling to organise holidays with your friends around the globe? Our site suggests the best destinations for travellers from differing destinations, optimised for cost, travel time, and budget!"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@triply_advisor"   # required for Twitter Cards
