module SearchHelper
  AMADEUS_SAMPLE = {

    "PAR" => [
      {"type" => "flight-offer",
        "id" => "1",
        "source" => "GDS",
        "instantTicketingRequired"=>false,
        "nonHomogeneous"=>false,
        "oneWay"=>false,
        "lastTicketingDate" => "2022-08-30",
        "numberOfBookableSeats"=>9,
        "itineraries"=>[{"duration" => "PT12H43M",
          "segments"=>[
            {
              "departure" => {"iataCode" => "CDG",
                "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},

              "carrierCode" => "AC",

              "number" => "871",

              "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},

 {"duration" => "PT11H26M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T13:29:00"},
 "arrival" => {"iataCode" => "IAD",
 "at" => "2022-10-22T16:02:00"},
 "carrierCode" => "UA",
 "number" => "2116",
 "aircraft" => {"code" => "319"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H33M",
 "id" => "11",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "IAD",
 "at" => "2022-10-22T17:25:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T06:55:00"},
 "carrierCode" => "UA",
 "number" => "915",
 "aircraft" => {"code" => "777"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H30M",
 "id" => "12",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "2",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT12H43M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},
 "carrierCode" => "AC",
 "number" => "871",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT13H41M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T12:04:00"},
 "arrival" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T15:03:00"},
 "carrierCode" => "UA",
 "number" => "2044",
 "aircraft" => {"code" => "7M8"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H59M",
 "id" => "15",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T18:30:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "UA",
 "number" => "57",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H15M",
 "id" => "16",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "3",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT12H43M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},
 "carrierCode" => "AC",
 "number" => "871",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT16H13M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T09:32:00"},
 "arrival" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T12:31:00"},
 "carrierCode" => "UA",
 "number" => "1799",
 "aircraft" => {"code" => "7M8"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H59M",
 "id" => "9",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T18:30:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "UA",
 "number" => "57",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H15M",
 "id" => "10",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "4",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT19H8M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T08:20:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T11:55:00"},
 "carrierCode" => "AC",
 "number" => "875",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT9H35M",
 "id" => "1",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "2",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT11H26M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T13:29:00"},
 "arrival" => {"iataCode" => "IAD",
 "at" => "2022-10-22T16:02:00"},
 "carrierCode" => "UA",
 "number" => "2116",
 "aircraft" => {"code" => "319"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H33M",
 "id" => "11",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "IAD",
 "at" => "2022-10-22T17:25:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T06:55:00"},
 "carrierCode" => "UA",
 "number" => "915",
 "aircraft" => {"code" => "777"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H30M",
 "id" => "12",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "11",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "12",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "5",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT19H8M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T08:20:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T11:55:00"},
 "carrierCode" => "AC",
 "number" => "875",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT9H35M",
 "id" => "1",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "2",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT13H41M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T12:04:00"},
 "arrival" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T15:03:00"},
 "carrierCode" => "UA",
 "number" => "2044",
 "aircraft" => {"code" => "7M8"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H59M",
 "id" => "15",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T18:30:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "UA",
 "number" => "57",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H15M",
 "id" => "16",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "15",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "16",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "6",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT19H8M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T08:20:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T11:55:00"},
 "carrierCode" => "AC",
 "number" => "875",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT9H35M",
 "id" => "1",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "2",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT16H13M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T09:32:00"},
 "arrival" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T12:31:00"},
 "carrierCode" => "UA",
 "number" => "1799",
 "aircraft" => {"code" => "7M8"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT2H59M",
 "id" => "9",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "EWR",
 "terminal" => "C",
 "at" => "2022-10-22T18:30:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "UA",
 "number" => "57",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "UA"},
 "duration" => "PT7H15M",
 "id" => "10",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "9",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "10",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "ECOBASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "7",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT12H43M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},
 "carrierCode" => "AC",
 "number" => "871",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT13H",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T12:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-22T16:08:00"},
 "carrierCode" => "AC",
 "number" => "1209",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H23M",
 "id" => "5",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-22T19:00:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "AC",
 "number" => "874",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT6H45M",
 "id" => "6",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "8",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT12H43M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},
 "carrierCode" => "AC",
 "number" => "871",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT15H",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T12:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-22T16:08:00"},
 "carrierCode" => "AC",
 "number" => "1209",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H23M",
 "id" => "7",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-22T21:05:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T09:45:00"},
 "carrierCode" => "AC",
 "number" => "870",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT6H40M",
 "id" => "8",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "7",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "8",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "9",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT12H43M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T14:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T16:20:00"},
 "carrierCode" => "AC",
 "number" => "871",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT7H35M",
 "id" => "3",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "4",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT17H35M",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T08:10:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-22T11:33:00"},
 "carrierCode" => "AC",
 "number" => "1207",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H23M",
 "id" => "13",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-22T19:00:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "AC",
 "number" => "874",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT6H45M",
 "id" => "14",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "3",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "4",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "13",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "14",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]}]},
 {"type" => "flight-offer",
 "id" => "10",
 "source" => "GDS",
 "instantTicketingRequired"=>false,
 "nonHomogeneous"=>false,
 "oneWay"=>false,
 "lastTicketingDate" => "2022-08-30",
 "numberOfBookableSeats"=>9,
 "itineraries"=>[{"duration" => "PT19H8M",
 "segments"=>[{"departure" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-16T08:20:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-16T11:55:00"},
 "carrierCode" => "AC",
 "number" => "875",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT9H35M",
 "id" => "1",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-16T18:00:00"},
 "arrival" => {"iataCode" => "MIA",
 "at" => "2022-10-16T21:28:00"},
 "carrierCode" => "AC",
 "number" => "1208",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H28M",
 "id" => "2",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]},
 {"duration" => "PT13H",
 "segments"=>[{"departure" => {"iataCode" => "MIA",
 "at" => "2022-10-22T12:45:00"},
 "arrival" => {"iataCode" => "YUL",
 "at" => "2022-10-22T16:08:00"},
 "carrierCode" => "AC",
 "number" => "1209",
 "aircraft" => {"code" => "223"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT3H23M",
 "id" => "5",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false},
 {"departure" => {"iataCode" => "YUL",
 "at" => "2022-10-22T19:00:00"},
 "arrival" => {"iataCode" => "CDG",
 "terminal" => "2A",
 "at" => "2022-10-23T07:45:00"},
 "carrierCode" => "AC",
 "number" => "874",
 "aircraft" => {"code" => "77W"},
 "operating" => {"carrierCode" => "AC"},
 "duration" => "PT6H45M",
 "id" => "6",
 "numberOfStops"=>0,
 "blacklistedInEU"=>false}]}],
 "price" => {"currency" => "EUR",
 "total" => "3632.86",
 "base" => "1540.00",
 "fees"=>[{"amount" => "0.00",
 "type" => "SUPPLIER"},
 {"amount" => "0.00",
 "type" => "TICKETING"}],
 "grandTotal" => "3632.86"},
 "pricingOptions" => {"fareType"=>["PUBLISHED"],
 "includedCheckedBagsOnly"=>false},
 "validatingAirlineCodes"=>["AC"],
 "travelerPricings"=>[{"travelerId" => "1",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "2",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "3",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "4",
 "fareOption" => "STANDARD",
 "travelerType" => "ADULT",
 "price" => {"currency" => "EUR",
 "total" => "628.81",
 "base" => "280.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L",
 "includedCheckedBags" => {"quantity"=>0}}]},
 {"travelerId" => "5",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]},
 {"travelerId" => "6",
 "fareOption" => "STANDARD",
 "travelerType" => "CHILD",
 "price" => {"currency" => "EUR",
 "total" => "558.81",
 "base" => "210.00"},
 "fareDetailsBySegment"=>[{"segmentId" => "1",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "2",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"},
 {"segmentId" => "5",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "class" => "L"},
 {"segmentId" => "6",
 "cabin" => "ECONOMY",
 "fareBasis" => "LLPU8LGT",
 "brandedFare" => "BASIC",
 "class" => "L"}]}]}],

    "LON" => [
  {
    "type" => "flight-offer",
    "id" => "1",
    "source" => "GDS",
    "instantTicketingRequired"=>false,
    "nonHomogeneous"=>false,
    "oneWay"=>false,
    "lastTicketingDate" => "2022-08-30",
    "numberOfBookableSeats"=>6,
    "itineraries"=>[
      {
        "duration" => "PT19H30M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-16T19:30:00"
            },
            "arrival" => {
              "iataCode" => "FRA",
              "terminal" => "1",
              "at" => "2022-10-16T22:10:00"
            },
            "carrierCode" => "LH",
            "number" => "919",
            "aircraft" => {
              "code" => "32N"
            },
            "operating" => {
              "carrierCode" => "LH"
            },
            "duration" => "PT1H40M",
            "id" => "3",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "FRA",
              "terminal" => "1",
              "at" => "2022-10-17T12:35:00"
            },
            "arrival" => {
              "iataCode" => "MIA",
              "at" => "2022-10-17T10:00:00"
            },
            "carrierCode" => "LH",
            "number" => "5007",
            "aircraft" => {
              "code" => "388"
            },
            "operating" => {
              "carrierCode" => "LH"
            },
            "duration" => "PT3H25M",
            "id" => "4",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      },

      {
        "duration" => "PT11H24M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "MIA",
              "at" => "2022-10-22T17:46:00"
            },
            "arrival" => {
              "iataCode" => "EWR",
              "terminal" => "C",
              "at" => "2022-10-22T20:47:00"
            },
            "carrierCode" => "LH",
            "number" => "8568",
            "aircraft" => {
              "code" => "739"
            },
            "operating" => {
              "carrierCode" => "UA"
            },
            "duration" => "PT3H1M",
            "id" => "15",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "EWR",
              "terminal" => "C",
              "at" => "2022-10-22T22:00:00"
            },
            "arrival" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-23T10:10:00"
            },
            "carrierCode" => "LH",
            "number" => "7628",
            "aircraft" => {
              "code" => "763"
            },
            "operating" => {
              "carrierCode" => "UA"
            },
            "duration" => "PT7H10M",
            "id" => "16",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      }
    ],
    "price" => {
      "currency" => "EUR",
      "total" => "5563.02",
      "base" => "3602.00",
      "fees"=>[
        {
          "amount" => "0.00",
          "type" => "SUPPLIER"
        },
        {
          "amount" => "0.00",
          "type" => "TICKETING"
        }
      ],
      "grandTotal" => "5563.02"
    },
    "pricingOptions" => {
      "fareType"=>[
        "PUBLISHED"
      ],
      "includedCheckedBagsOnly"=>false
    },
    "validatingAirlineCodes"=>[
      "LH"
    ],
    "travelerPricings"=>[
      {
        "travelerId" => "1",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1568.98",
          "base" => "1029.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "15",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "16",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "2",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1568.98",
          "base" => "1029.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "15",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "16",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "3",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1212.53",
          "base" => "772.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          },
          {
            "segmentId" => "15",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "16",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          }
        ]
      },
      {
        "travelerId" => "4",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1212.53",
          "base" => "772.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          },
          {
            "segmentId" => "15",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "16",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          }
        ]
      }
    ]
  },
  {
    "type" => "flight-offer",
    "id" => "2",
    "source" => "GDS",
    "instantTicketingRequired"=>false,
    "nonHomogeneous"=>false,
    "oneWay"=>false,
    "lastTicketingDate" => "2022-08-30",
    "numberOfBookableSeats"=>6,
    "itineraries"=>[
      {
        "duration" => "PT19H30M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-16T19:30:00"
            },
            "arrival" => {
              "iataCode" => "FRA",
              "terminal" => "1",
              "at" => "2022-10-16T22:10:00"
            },
            "carrierCode" => "LH",
            "number" => "919",
            "aircraft" => {
              "code" => "32N"
            },
            "operating" => {
              "carrierCode" => "LH"
            },
            "duration" => "PT1H40M",
            "id" => "3",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "FRA",
              "terminal" => "1",
              "at" => "2022-10-17T12:35:00"
            },
            "arrival" => {
              "iataCode" => "MIA",
              "at" => "2022-10-17T10:00:00"
            },
            "carrierCode" => "LH",
            "number" => "5007",
            "aircraft" => {
              "code" => "388"
            },
            "operating" => {
              "carrierCode" => "LH"
            },
            "duration" => "PT3H25M",
            "id" => "4",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      },
      {
        "duration" => "PT12H19M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "MIA",
              "at" => "2022-10-22T17:46:00"
            },
            "arrival" => {
              "iataCode" => "EWR",
              "terminal" => "C",
              "at" => "2022-10-22T20:47:00"
            },
            "carrierCode" => "LH",
            "number" => "8568",
            "aircraft" => {
              "code" => "739"
            },
            "operating" => {
              "carrierCode" => "UA"
            },
            "duration" => "PT3H1M",
            "id" => "11",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "EWR",
              "terminal" => "C",
              "at" => "2022-10-22T23:00:00"
            },
            "arrival" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-23T11:05:00"
            },
            "carrierCode" => "LH",
            "number" => "7630",
            "aircraft" => {
              "code" => "763"
            },
            "operating" => {
              "carrierCode" => "UA"
            },
            "duration" => "PT7H5M",
            "id" => "12",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      }
    ],
    "price" => {
      "currency" => "EUR",
      "total" => "5563.02",
      "base" => "3602.00",
      "fees"=>[
        {
          "amount" => "0.00",
          "type" => "SUPPLIER"
        },
        {
          "amount" => "0.00",
          "type" => "TICKETING"
        }
      ],
      "grandTotal" => "5563.02"
    },
    "pricingOptions" => {
      "fareType"=>[
        "PUBLISHED"
      ],
      "includedCheckedBagsOnly"=>false
    },
    "validatingAirlineCodes"=>[
      "LH"
    ],
    "travelerPricings"=>[
      {
        "travelerId" => "1",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1568.98",
          "base" => "1029.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "11",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "12",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "2",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1568.98",
          "base" => "1029.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "11",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "12",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "3",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1212.53",
          "base" => "772.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          },
          {
            "segmentId" => "11",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "12",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          }
        ]
      },
      {
        "travelerId" => "4",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1212.53",
          "base" => "772.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "3",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "4",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKXB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          },
          {
            "segmentId" => "11",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "12",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "ECOLIGHT",
            "class" => "U"
          }
        ]
      }
    ]
  },
  {
    "type" => "flight-offer",
    "id" => "3",
    "source" => "GDS",
    "instantTicketingRequired"=>false,
    "nonHomogeneous"=>false,
    "oneWay"=>false,
    "lastTicketingDate" => "2022-08-30",
    "numberOfBookableSeats"=>9,
    "itineraries"=>[
      {
        "duration" => "PT12H23M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-16T14:05:00"
            },
            "arrival" => {
              "iataCode" => "YUL",
              "at" => "2022-10-16T16:15:00"
            },
            "carrierCode" => "AC",
            "number" => "865",
            "aircraft" => {
              "code" => "789"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT7H10M",
            "id" => "1",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "YUL",
              "at" => "2022-10-16T18:00:00"
            },
            "arrival" => {
              "iataCode" => "MIA",
              "at" => "2022-10-16T21:28:00"
            },
            "carrierCode" => "AC",
            "number" => "1208",
            "aircraft" => {
              "code" => "223"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT3H28M",
            "id" => "2",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      },
      {
        "duration" => "PT12H45M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "MIA",
              "at" => "2022-10-22T12:45:00"
            },
            "arrival" => {
              "iataCode" => "YUL",
              "at" => "2022-10-22T16:08:00"
            },
            "carrierCode" => "AC",
            "number" => "1209",
            "aircraft" => {
              "code" => "223"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT3H23M",
            "id" => "17",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "YUL",
              "at" => "2022-10-22T19:00:00"
            },
            "arrival" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-23T06:30:00"
            },
            "carrierCode" => "AC",
            "number" => "864",
            "aircraft" => {
              "code" => "789"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT6H30M",
            "id" => "18",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      }
    ],
    "price" => {
      "currency" => "EUR",
      "total" => "5589.66",
      "base" => "3726.00",
      "fees"=>[
        {
          "amount" => "0.00",
          "type" => "SUPPLIER"
        },
        {
          "amount" => "0.00",
          "type" => "TICKETING"
        }
      ],
      "grandTotal" => "5589.66"
    },
    "pricingOptions" => {
      "fareType"=>[
        "PUBLISHED"
      ],
      "includedCheckedBagsOnly"=>false
    },
    "validatingAirlineCodes"=>[
      "AC"
    ],
    "travelerPricings"=>[
      {
        "travelerId" => "1",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1580.64",
          "base" => "1065.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "1",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "2",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "2",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1580.64",
          "base" => "1065.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "1",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "2",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "3",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1214.19",
          "base" => "798.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "1",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "2",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          }
        ]
      },
      {
        "travelerId" => "4",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1214.19",
          "base" => "798.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "1",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "2",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          }
        ]
      }
    ]
  },
  {
    "type" => "flight-offer",
    "id" => "4",
    "source" => "GDS",
    "instantTicketingRequired"=>false,
    "nonHomogeneous"=>false,
    "oneWay"=>false,
    "lastTicketingDate" => "2022-08-30",
    "numberOfBookableSeats"=>9,
    "itineraries"=>[
      {
        "duration" => "PT16H58M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-16T09:30:00"
            },
            "arrival" => {
              "iataCode" => "YUL",
              "at" => "2022-10-16T11:40:00"
            },
            "carrierCode" => "AC",
            "number" => "867",
            "aircraft" => {
              "code" => "788"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT7H10M",
            "id" => "9",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "YUL",
              "at" => "2022-10-16T18:00:00"
            },
            "arrival" => {
              "iataCode" => "MIA",
              "at" => "2022-10-16T21:28:00"
            },
            "carrierCode" => "AC",
            "number" => "1208",
            "aircraft" => {
              "code" => "223"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT3H28M",
            "id" => "10",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      },
      {
        "duration" => "PT12H45M",
        "segments"=>[
          {
            "departure" => {
              "iataCode" => "MIA",
              "at" => "2022-10-22T12:45:00"
            },
            "arrival" => {
              "iataCode" => "YUL",
              "at" => "2022-10-22T16:08:00"
            },
            "carrierCode" => "AC",
            "number" => "1209",
            "aircraft" => {
              "code" => "223"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT3H23M",
            "id" => "17",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          },
          {
            "departure" => {
              "iataCode" => "YUL",
              "at" => "2022-10-22T19:00:00"
            },
            "arrival" => {
              "iataCode" => "LHR",
              "terminal" => "2",
              "at" => "2022-10-23T06:30:00"
            },
            "carrierCode" => "AC",
            "number" => "864",
            "aircraft" => {
              "code" => "789"
            },
            "operating" => {
              "carrierCode" => "AC"
            },
            "duration" => "PT6H30M",
            "id" => "18",
            "numberOfStops"=>0,
            "blacklistedInEU"=>false
          }
        ]
      }
    ],
    "price" => {
      "currency" => "EUR",
      "total" => "5589.66",
      "base" => "3726.00",
      "fees"=>[
        {
          "amount" => "0.00",
          "type" => "SUPPLIER"
        },
        {
          "amount" => "0.00",
          "type" => "TICKETING"
        }
      ],
      "grandTotal" => "5589.66"
    },
    "pricingOptions" => {
      "fareType"=>[
        "PUBLISHED"
      ],
      "includedCheckedBagsOnly"=>false
    },
    "validatingAirlineCodes"=>[
      "AC"
    ],
    "travelerPricings"=>[
      {
        "travelerId" => "1",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1580.64",
          "base" => "1065.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "9",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "10",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "2",
        "fareOption" => "STANDARD",
        "travelerType" => "ADULT",
        "price" => {
          "currency" => "EUR",
          "total" => "1580.64",
          "base" => "1065.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "9",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "10",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U",
            "includedCheckedBags" => {
              "quantity"=>0
            }
          }
        ]
      },
      {
        "travelerId" => "3",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1214.19",
          "base" => "798.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "9",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "10",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          }
        ]
      },
      {
        "travelerId" => "4",
        "fareOption" => "STANDARD",
        "travelerType" => "CHILD",
        "price" => {
          "currency" => "EUR",
          "total" => "1214.19",
          "base" => "798.00"
        },
        "fareDetailsBySegment"=>[
          {
            "segmentId" => "9",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "10",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          },
          {
            "segmentId" => "17",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "class" => "U"
          },
          {
            "segmentId" => "18",
            "cabin" => "ECONOMY",
            "fareBasis" => "UKWB3LGT",
            "brandedFare" => "BASIC",
            "class" => "U"
          }
        ]
      }
    ]
  }
  ]
}
end
